apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-controller-ingress
  namespace: lab-controller
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: labcontroller-blue.talentos.darey.io
    external-dns.alpha.kubernetes.io/manage: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - labcontroller-blue.talentos.darey.io
        - labcontroller.talentos.darey.io
      secretName: labcontroller-tls
  rules:
    - host: labcontroller-blue.talentos.darey.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab-controller
                port:
                  number: 80
    - host: labcontroller.talentos.darey.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab-controller
                port:
                  number: 80
