apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-controller

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - podmonitor.yaml

images:
  - name: lab-controller-api
    newName: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/lab-controller/labcontroller-api
    newTag: 7876f4246a018021f775f321622862eddb109c1e

