apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-controller

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - podmonitor.yaml

images:
  - name: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/lab-controller/labcontroller-api
    newName: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/lab-controller/labcontroller-api
    newTag: 5491974-amd64

