apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liveclasses

resources:
  # BBB resources removed - files kept in ../bbb/ directory but not deployed
  # Jitsi resources
  - ../prosody-deployment.yaml
  - ../service.yaml
  - ../jicofo-deployment.yaml
  - ../jvb-deployment.yaml
  - ../jitsi-web-deployment.yaml
  - ../jibri-deployment.yaml
  - ../jibri-configmap.yaml
  - ../jibri-serviceaccount.yaml
  - ../jitsi-web-configmap.yaml
  - ../configmap.yaml
  - ../external-secret.yaml
  - ../custom-css.yaml
  - ../auto-tileview.yaml
  - ../move-sidebar.yaml
  - ../head-injection.yaml
  - ../nginx-config.yaml
  - ../servicemonitor-jicofo.yaml
  - ../servicemonitor-jitsi-web.yaml
  - ../servicemonitor-jvb.yaml

