apiVersion: apps/v1
kind: Deployment
metadata:
  name: dareyscore-api
  namespace: dareyscore
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dareyscore-api
  template:
    metadata:
      labels:
        app: dareyscore-api
    spec:
      nodeSelector:
        capacity-type: SPOT
      tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      serviceAccountName: dareyscore-sa
      containers:
        - name: api
          image: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/dareyscore/dareyscore-api:41d2c50ffec315c9f05c9b8b5a573f050ab309c2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          envFrom:
            - configMapRef:
                name: dareyscore-config
            - secretRef:
                name: dareyscore-api-secrets
          env:
            - name: SERVICE_NAME
              value: dareyscore-api
            - name: SERVICE_NAMESPACE
              value: dareyscore
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: dareyscore-config
                  key: OTLP_ENDPOINT
            - name: OTEL_EXPORTER_OTLP_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: dareyscore-config
                  key: OTLP_INSECURE
            - name: OTEL_SERVICE_NAME
              value: dareyscore-api
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=dareyscore,service.instance.id=$(HOSTNAME)"
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 8
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
