apiVersion: apps/v1
kind: Deployment
metadata:
  name: dareyscore-worker
  namespace: dareyscore
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dareyscore-worker
  template:
    metadata:
      labels:
        app: dareyscore-worker
    spec:
      nodeSelector:
        capacity-type: SPOT
      tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      serviceAccountName: dareyscore-sa
      containers:
        - name: worker
          image: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/dareyscore/dareyscore-worker:0697c28911b198d0859f7bd994cb9246441b1bfd
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dareyscore-config
            - secretRef:
                name: dareyscore-api-secrets
          env:
            - name: SERVICE_NAME
              value: dareyscore-worker
            - name: SERVICE_NAMESPACE
              value: dareyscore
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: dareyscore-config
                  key: OTLP_ENDPOINT
            - name: OTEL_EXPORTER_OTLP_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: dareyscore-config
                  key: OTLP_INSECURE
            - name: OTEL_SERVICE_NAME
              value: dareyscore-worker
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=dareyscore,service.instance.id=$(HOSTNAME)"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
