---
# Jicofo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  namespace: liveclasses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - jicofo
                        - jibri
                        - jvb
                topologyKey: kubernetes.io/hostname
      containers:
        - name: jicofo
          image: jitsi/jicofo:jicofo-1.0-1148-1
          resources:
            requests:
              cpu: "300m"
              memory: "384Mi"
            limits:
              cpu: "800m"
              memory: "768Mi"
          env:
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-auth-secrets
                  key: JICOFO_AUTH_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: jicofo
  namespace: liveclasses
spec:
  selector:
    app: jicofo
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: http
  type: ClusterIP
