apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-meet-nginx-config
  namespace: liveclasses
data:
  meet.conf: |
    server_name _;

    charset utf8;

    client_max_body_size 0;

    root /usr/share/jitsi-meet;

    ssi on;
    ssi_types application/x-javascript application/javascript;

    index index.html index.htm;
    error_page 404 /static/404.html;

    # Security headers
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Permissions-Policy "interest-cohort=()";

    set $prefix "";

    include /config/nginx-custom/*.conf;

    location = /config.js {
        alias /usr/share/jitsi-meet/config.js;
    }

    location = /interface_config.js {
        alias /usr/share/jitsi-meet/interface_config.js;
    }

    location = /external_api.js {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Origin, X-Requested-With, Content-Type, Accept' always;
        alias /usr/share/jitsi-meet/libs/external_api.min.js;
    }

    location ~ ^/(libs|css|static|images|fonts|lang|sounds|connection_optimization|.well-known|transcripts)/(.*)$ {
        add_header 'Access-Control-Allow-Origin' '*';
        alias /usr/share/jitsi-meet/$1/$2;

        if ($arg_v) {
            expires 1y;
        }
    }

    location = /http-bind {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host streaming-stg.talentos.darey.io;
        proxy_pass http://prosody.liveclasses.svc.cluster.local:5280/http-bind?prefix=$prefix&$args;
    }

    location = /xmpp-websocket {
        tcp_nodelay on;
        proxy_http_version 1.1;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host streaming-stg.talentos.darey.io;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://prosody.liveclasses.svc.cluster.local:5280/xmpp-websocket?prefix=$prefix&$args;
    }

    location ~ ^/([^/?&:'"]+)$ {
        try_files $uri @root_path;
    }

    location @root_path {
        rewrite ^/(.*)$ / break;
    }

    location ~ ^/([^/?&:'"]+)/(pwa-worker.js|manifest.json)$ {
        set $subdomain "$1.";
        set $subdir "$1/";
        rewrite ^/([^/?&:'"]+)/(pwa-worker.js|manifest.json)$ /$2;
    }

    location ~ ^/([^/?&:'"]+)/config.js$ {
        set $subdomain "$1.";
        set $subdir "$1/";
        alias /usr/share/jitsi-meet/config.js;
    }

    location ~ ^/([^/?&:'"]+)/http-bind {
        set $subdomain "$1.";
        set $subdir "$1/";
        set $prefix "$1";
        rewrite ^/(.*)$ /http-bind;
    }

    location ~ ^/([^/?&:'"]+)/xmpp-websocket {
        set $subdomain "$1.";
        set $subdir "$1/";
        set $prefix "$1";
        rewrite ^/(.*)$ /xmpp-websocket;
    }

    location ~ ^/([^/?&:'"]+)/(.*)$ {
        set $subdomain "$1.";
        set $subdir "$1/";
        rewrite ^/([^/?&:'"]+)/(.*)$ /$2;
    }
