# Prosody Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: liveclasses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - name: prosody
          image: jitsi/prosody:prosody-13.0.2
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
          ports:
            - containerPort: 5222
            - containerPort: 5280
            - containerPort: 5347
          env:
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-auth-secrets
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-auth-secrets
                  key: JVB_AUTH_PASSWORD
            - name: JIBRI_XMPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-auth-secrets
                  key: JIBRI_XMPP_PASSWORD
            - name: JIBRI_RECORDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-auth-secrets
                  key: JIBRI_RECORDER_PASSWORD
            - name: JWT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-jwt-secret
                  key: JITSI_JWT_SECRET
            - name: JWT_APP_ID
              value: "darey-io"
            - name: JWT_ACCEPTED_ISSUERS
              value: "darey-io"
            - name: JWT_ACCEPTED_AUDIENCES
              value: "jitsi"
          volumeMounts:
            - name: prosody-config
              mountPath: /config/conf.d/streaming-stg.talentos.darey.io.cfg.lua
              subPath: streaming-stg.talentos.darey.io.cfg.lua
      volumes:
        - name: prosody-config
          configMap:
            name: prosody-custom-config
