apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liveclasses-streaming-ingress
  namespace: liveclasses
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: streaming.talentos.darey.io
    external-dns.alpha.kubernetes.io/manage: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: streaming.talentos.darey.io
      http:
        paths:
          # BBB API service
          - path: /bbb/api
            pathType: Prefix
            backend:
              service:
                name: liveclasses-bbb-api
                port:
                  number: 8080
          # BBB web interface (when deployed)
          - path: /bbb
            pathType: Prefix
            backend:
              service:
                name: bbb-web
                port:
                  number: 80
          # Default root path - routes to BBB API (can be changed by updating this ingress)
          # To change default provider, update the service name below
          - path: /
            pathType: Prefix
            backend:
              service:
                name: liveclasses-bbb-api
                port:
                  number: 8080
  tls:
    - hosts:
        - streaming.talentos.darey.io
      secretName: liveclasses-tls-cert
