apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liveclasses

resources:
  - ../../base

# Patch ConfigMap to disable Jitsi
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: liveclasses-config
    data:
      jitsi_enabled: "false"

