apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-api
  namespace: liveclasses
  labels:
    app: bbb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bbb-api
  template:
    metadata:
      labels:
        app: bbb-api
    spec:
      containers:
        - name: bbb-api
          image: 586794457112.dkr.ecr.eu-west-2.amazonaws.com/liveclasses/bbb-web:3.0.4
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8090
              protocol: TCP
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-0.mongodb.liveclasses.svc.cluster.local:27017,mongodb-1.mongodb.liveclasses.svc.cluster.local:27017,mongodb-2.mongodb.liveclasses.svc.cluster.local:27017/bigbluebutton?replicaSet=bbb-rs"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: database-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: database-password
            - name: BBB_SALT
              valueFrom:
                secretKeyRef:
                  name: bbb-secrets
                  key: api-secret
            - name: BBB_URL
              value: "https://streaming-stg.talentos.darey.io"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /bigbluebutton/api
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /bigbluebutton/api
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

