apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liveclasses

resources:
  - ../namespace.yaml
  - ../configmap.yaml
  - ../liveclasses-recordings-serviceaccount.yaml
  - ../ingress.yaml
  - ../bbb/bbb-api-deployment.yaml
  - ../bbb/bbb-api-service.yaml
  - ../bbb/bbb-web-deployment.yaml
  - ../bbb/bbb-web-service.yaml
  - ../bbb/bbb-nginx-deployment.yaml
  - ../bbb/freeswitch-daemonset.yaml
  - ../bbb/freeswitch-service.yaml
  - ../bbb/kurento-daemonset.yaml
  - ../bbb/kurento-service.yaml

