apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liveclasses

resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../liveclasses-recordings-serviceaccount.yaml
  - ../../ingress.yaml
  - ../bbb-api-deployment.yaml
  - ../bbb-api-service.yaml
  - ../bbb-web-deployment.yaml
  - ../bbb-web-service.yaml
  - ../bbb-nginx-deployment.yaml
  - ../freeswitch-daemonset.yaml
  - ../freeswitch-service.yaml
  - ../kurento-daemonset.yaml
  - ../kurento-service.yaml
  - ../mongodb-statefulset.yaml
  - ../mongodb-service.yaml
  - ../mongodb-configmap.yaml
  - ../mongodb-secret.yaml
  - ../mongodb-keyfile-externalsecret.yaml
  - ../mongodb-secret-externalsecret.yaml
  - ../mongodb-pdb.yaml
  - ../mongodb-backup-cronjob.yaml
  - ../mongodb-backup-serviceaccount.yaml
  - ../bbb-secret-externalsecret.yaml

# Note: Jitsi resources are intentionally excluded from base
# They should only be included when explicitly enabled via overlay
