serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::586794457112:role/darey-io-v2-lab-prod-karpenter-controller
settings:
  aws:
    clusterName: darey-io-v2-lab-prod
    defaultInstanceProfile: darey-io-v2-lab-prod-karpenter-instance-profile
    interruptionQueueName: darey-io-v2-lab-prod-karpenter-interruptions
  clusterName: darey-io-v2-lab-prod
controller:
  env:
  - name: AWS_REGION
    value: eu-west-2
  - name: AWS_DEFAULT_REGION
    value: eu-west-2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.sh/nodepool
            operator: In
            values:
            - general-purpose
  tolerations: []
