apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: liveclasses
spec:
  selector:
    app: prosody
  ports:
    - name: xmpp
      protocol: TCP
      port: 5222
      targetPort: 5222
    - name: bosh
      protocol: TCP
      port: 5280
      targetPort: 5280
  type: ClusterIP
