apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whatsapp-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: whatsapp-webhook
    creationPolicy: Owner
  data:
    - secretKey: whatsapp_api_token
      remoteRef:
        key: monitoring/alertmanager-whatsapp
        property: api_token

