apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dareyscore-ingress
  namespace: dareyscore
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: dareyscore-green.talentos.darey.io
    external-dns.alpha.kubernetes.io/manage: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dareyscore-green.talentos.darey.io
        - dareyscore.talentos.darey.io
      secretName: dareyscore-tls
  rules:
    - host: dareyscore-green.talentos.darey.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dareyscore-api
                port:
                  number: 80
    - host: dareyscore.talentos.darey.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dareyscore-api
                port:
                  number: 80
